services:
  postgres:
    image: bitnami/postgresql:16.2.0
    container_name: postgres
    environment:
      POSTGRES_DB: benjifa_oauth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - benji_network

  redis:
    image: redis:7.2.4
    tty: true
    stdin_open: true
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: admin
    networks:
      - benji_network

  app:
    container_name: benji_oauth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/benjifa_oauth_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: admin
    networks:
      - benji_network

volumes:
  postgres_data:
    driver: local

networks:
  benji_network:
    driver: bridge

