spring:
    application:
        name: benjfa-oauth-service

    datasource:
        url: jdbc:postgresql://localhost:5432/benjifa_oauth_db
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    cache:
        redis:
            cache-null-values: false
            key-prefix: tokens
            time-to-live: 60000000
            use-key-prefix: true
            enable-statistics: true
            cache-names: benji-cache
            type: redis
server:
    port: 9000

logging:
    level:
        root: warn
        org.springframework.security: trace
        org.springframework.security.oauth2: trace
        org.springframework.web: warn
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        correlation: "%X{X-B3-TraceId:-} %X{X-B3-SpanId:-} %X{X-Span-Export:-}"
    file:
        name: benjifa-oauth.log
        path: /var/log/benjfa-oauth-service/

    charset:
        console: UTF-8
        file: UTF-8

jwt:
  expiration: 864000000
  refresh-expiration: 8640000000
  header: Authorization
  prefix: Bearer
  secret: benji-secretN6qMkW-OKUM4MjjnoM-2KHvisVPNYedft1g5z_0g4lrOXXlcSYGjviOZttkCu_JtiQQhitErLeMMtaXsjlMW7Q
  issuer: benji.social


pics:
  baseUrl: https://picsum.photos/id/0/5000/3333



management:
  endpoints:
    web:
      exposure:
        include: '*'